/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'other' : IDL.Null,
  'marketing' : IDL.Null,
  'saas' : IDL.Null,
  'office' : IDL.Null,
  'legal' : IDL.Null,
  'infrastructure' : IDL.Null,
  'payroll' : IDL.Null,
});
export const Type__3 = IDL.Record({
  'description' : IDL.Text,
  'category' : IDL.Text,
  'currentSpend' : IDL.Float64,
  'averageSpend' : IDL.Float64,
});
export const Type__2 = IDL.Record({
  'runwayMonths' : IDL.Float64,
  'avgMonthlySpend' : IDL.Float64,
  'totalSpent' : IDL.Float64,
  'runwayText' : IDL.Text,
  'monthlyBurnRate' : IDL.Float64,
});
export const Settings = IDL.Record({
  'fakeDataMode' : IDL.Bool,
  'connectedAccount' : IDL.Text,
  'fundingAmount' : IDL.Float64,
  'startingBalance' : IDL.Float64,
});
export const Type__1 = IDL.Record({
  'id' : IDL.Nat,
  'source' : IDL.Text,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'category' : Category,
  'amount' : IDL.Float64,
});
export const Type = IDL.Record({
  'anomalyDetected' : IDL.Bool,
  'anomalyDetails' : IDL.Text,
  'totalSpend' : IDL.Float64,
  'topCategory' : IDL.Text,
});

export const idlService = IDL.Service({
  'addTransaction' : IDL.Func(
      [IDL.Int, IDL.Text, IDL.Float64, Category, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'clearData' : IDL.Func([], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'detectAnomalies' : IDL.Func([], [IDL.Vec(Type__3)], ['query']),
  'getBurnRateSummary' : IDL.Func([], [Type__2], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getTotalExpensesByCategory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getTransactions' : IDL.Func([], [IDL.Vec(Type__1)], ['query']),
  'getWeeklySummary' : IDL.Func([], [Type], ['query']),
  'saveSettings' : IDL.Func([Settings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'other' : IDL.Null,
    'marketing' : IDL.Null,
    'saas' : IDL.Null,
    'office' : IDL.Null,
    'legal' : IDL.Null,
    'infrastructure' : IDL.Null,
    'payroll' : IDL.Null,
  });
  const Type__3 = IDL.Record({
    'description' : IDL.Text,
    'category' : IDL.Text,
    'currentSpend' : IDL.Float64,
    'averageSpend' : IDL.Float64,
  });
  const Type__2 = IDL.Record({
    'runwayMonths' : IDL.Float64,
    'avgMonthlySpend' : IDL.Float64,
    'totalSpent' : IDL.Float64,
    'runwayText' : IDL.Text,
    'monthlyBurnRate' : IDL.Float64,
  });
  const Settings = IDL.Record({
    'fakeDataMode' : IDL.Bool,
    'connectedAccount' : IDL.Text,
    'fundingAmount' : IDL.Float64,
    'startingBalance' : IDL.Float64,
  });
  const Type__1 = IDL.Record({
    'id' : IDL.Nat,
    'source' : IDL.Text,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'category' : Category,
    'amount' : IDL.Float64,
  });
  const Type = IDL.Record({
    'anomalyDetected' : IDL.Bool,
    'anomalyDetails' : IDL.Text,
    'totalSpend' : IDL.Float64,
    'topCategory' : IDL.Text,
  });
  
  return IDL.Service({
    'addTransaction' : IDL.Func(
        [IDL.Int, IDL.Text, IDL.Float64, Category, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'clearData' : IDL.Func([], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'detectAnomalies' : IDL.Func([], [IDL.Vec(Type__3)], ['query']),
    'getBurnRateSummary' : IDL.Func([], [Type__2], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getTotalExpensesByCategory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getTransactions' : IDL.Func([], [IDL.Vec(Type__1)], ['query']),
    'getWeeklySummary' : IDL.Func([], [Type], ['query']),
    'saveSettings' : IDL.Func([Settings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };