/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'other' : null } |
  { 'marketing' : null } |
  { 'saas' : null } |
  { 'office' : null } |
  { 'legal' : null } |
  { 'infrastructure' : null } |
  { 'payroll' : null };
export interface Settings {
  'fakeDataMode' : boolean,
  'connectedAccount' : string,
  'fundingAmount' : number,
  'startingBalance' : number,
}
export interface Type {
  'anomalyDetected' : boolean,
  'anomalyDetails' : string,
  'totalSpend' : number,
  'topCategory' : string,
}
export interface Type__1 {
  'id' : bigint,
  'source' : string,
  'date' : bigint,
  'description' : string,
  'category' : Category,
  'amount' : number,
}
export interface Type__2 {
  'runwayMonths' : number,
  'avgMonthlySpend' : number,
  'totalSpent' : number,
  'runwayText' : string,
  'monthlyBurnRate' : number,
}
export interface Type__3 {
  'description' : string,
  'category' : string,
  'currentSpend' : number,
  'averageSpend' : number,
}
export interface _SERVICE {
  'addTransaction' : ActorMethod<
    [bigint, string, number, Category, string],
    bigint
  >,
  'clearData' : ActorMethod<[], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'detectAnomalies' : ActorMethod<[], Array<Type__3>>,
  'getBurnRateSummary' : ActorMethod<[], Type__2>,
  'getSettings' : ActorMethod<[], Settings>,
  'getTotalExpensesByCategory' : ActorMethod<[], Array<[string, number]>>,
  'getTransactions' : ActorMethod<[], Array<Type__1>>,
  'getWeeklySummary' : ActorMethod<[], Type>,
  'saveSettings' : ActorMethod<[Settings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];