/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Type__3 {
    description: string;
    category: string;
    currentSpend: number;
    averageSpend: number;
}
export interface Type__1 {
    id: bigint;
    source: string;
    date: bigint;
    description: string;
    category: Category;
    amount: number;
}
export interface Type {
    anomalyDetected: boolean;
    anomalyDetails: string;
    totalSpend: number;
    topCategory: string;
}
export interface Settings {
    fakeDataMode: boolean;
    connectedAccount: string;
    fundingAmount: number;
    startingBalance: number;
}
export interface Type__2 {
    runwayMonths: number;
    avgMonthlySpend: number;
    totalSpent: number;
    runwayText: string;
    monthlyBurnRate: number;
}
export enum Category {
    other = "other",
    marketing = "marketing",
    saas = "saas",
    office = "office",
    legal = "legal",
    infrastructure = "infrastructure",
    payroll = "payroll"
}
export interface backendInterface {
    addTransaction(date: bigint, description: string, amount: number, category: Category, source: string): Promise<bigint>;
    clearData(): Promise<void>;
    deleteTransaction(id: bigint): Promise<void>;
    detectAnomalies(): Promise<Array<Type__3>>;
    getBurnRateSummary(): Promise<Type__2>;
    getSettings(): Promise<Settings>;
    getTotalExpensesByCategory(): Promise<Array<[string, number]>>;
    getTransactions(): Promise<Array<Type__1>>;
    getWeeklySummary(): Promise<Type>;
    saveSettings(newSettings: Settings): Promise<void>;
}
import type { Category as _Category, Type__1 as _Type__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addTransaction(arg0: bigint, arg1: string, arg2: number, arg3: Category, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, arg1, arg2, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, arg1, arg2, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async clearData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearData();
            return result;
        }
    }
    async deleteTransaction(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async detectAnomalies(): Promise<Array<Type__3>> {
        if (this.processError) {
            try {
                const result = await this.actor.detectAnomalies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.detectAnomalies();
            return result;
        }
    }
    async getBurnRateSummary(): Promise<Type__2> {
        if (this.processError) {
            try {
                const result = await this.actor.getBurnRateSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBurnRateSummary();
            return result;
        }
    }
    async getSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async getTotalExpensesByCategory(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalExpensesByCategory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalExpensesByCategory();
            return result;
        }
    }
    async getTransactions(): Promise<Array<Type__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklySummary(): Promise<Type> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklySummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklySummary();
            return result;
        }
    }
    async saveSettings(arg0: Settings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSettings(arg0);
            return result;
        }
    }
}
function from_candid_Category_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Type__1_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__1): Type__1 {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    source: string;
    date: bigint;
    description: string;
    category: _Category;
    amount: number;
}): {
    id: bigint;
    source: string;
    date: bigint;
    description: string;
    category: Category;
    amount: number;
} {
    return {
        id: value.id,
        source: value.source,
        date: value.date,
        description: value.description,
        category: from_candid_Category_n6(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    marketing: null;
} | {
    saas: null;
} | {
    office: null;
} | {
    legal: null;
} | {
    infrastructure: null;
} | {
    payroll: null;
}): Category {
    return "other" in value ? Category.other : "marketing" in value ? Category.marketing : "saas" in value ? Category.saas : "office" in value ? Category.office : "legal" in value ? Category.legal : "infrastructure" in value ? Category.infrastructure : "payroll" in value ? Category.payroll : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Type__1>): Array<Type__1> {
    return value.map((x)=>from_candid_Type__1_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    other: null;
} | {
    marketing: null;
} | {
    saas: null;
} | {
    office: null;
} | {
    legal: null;
} | {
    infrastructure: null;
} | {
    payroll: null;
} {
    return value == Category.other ? {
        other: null
    } : value == Category.marketing ? {
        marketing: null
    } : value == Category.saas ? {
        saas: null
    } : value == Category.office ? {
        office: null
    } : value == Category.legal ? {
        legal: null
    } : value == Category.infrastructure ? {
        infrastructure: null
    } : value == Category.payroll ? {
        payroll: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
